{{- if .Values.ltc.legacy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litecoind-legacy
  namespace: {{ .Values.namespace }}
  labels:
    app: litecoind-legacy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: litecoind-legacy
  template:
    metadata:
      labels:
        app: litecoind-legacy
    spec:
      containers:
      - name: litecoind
        image: {{ .Values.ltc_fullnode.image }}
        command:
        - /shkeeper/litecoind
        - -rpcport=9332
        - -prune=550
        - -rpcpassword=$(LTC_PASSWORD)
        - -rpcuser=$(LTC_USERNAME)
        - -rpcbind=0.0.0.0
        - -rpcallowip=0.0.0.0/0
        - -wallet=shkeeper
        #- -walletnotify=/shkeeper/walletnotify.sh %s
        {{- if not .Values.ltc.mainnet }}
        - -testnet
        {{- end }}
        env:
          - name: LTC_USERNAME
            valueFrom:
              secretKeyRef:
                name: litecoin-rpc
                key: username
                optional: false
          - name: LTC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: litecoin-rpc
                key: password
                optional: false
          - name: SHKEEPER_BACKEND_KEY
            valueFrom:
              secretKeyRef:
                name: shkeeper-btc-key
                key: password
                optional: false
        volumeMounts:
        - name: litecoind-storage
          mountPath: /root/.litecoin
      volumes:
      - name: litecoind-storage
        persistentVolumeClaim:
          claimName: litecoind-legacy
{{- end }}