apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      hostname: mariadb
      containers:
      - name: mariadb
        image: mariadb:10.9.3
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: shkeeper
        volumeMounts:
        - name: mariadb
          mountPath: /var/lib/mysql
        - name: mariadb-docker-entrypoint-initdb-d
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: mariadb
      - name: mariadb-docker-entrypoint-initdb-d
        configMap:
          name: mariadb-docker-entrypoint-initdb-d
