{{- if or .Values.aml.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: aml-shkeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: aml-shkeeper
  ports:
  - name: app-tcp
    port: 6000
    protocol: TCP
{{ end }}
