{{- if or .Values.eth.enabled .Values.eth_usdt.enabled .Values.eth_usdc.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-shkeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ethereum-shkeeper
  ports:
  - name: app-tcp
    port: 6000
    protocol: TCP
{{ end }}
