{{- if or .Values.opeth.enabled .Values.op_token.enabled .Values.op_usdc.enabled .Values.op_usdt.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: optimism-shkeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: optimism-shkeeper
  ports:
  - name: app-tcp
    port: 6000
    protocol: TCP
{{ end }}
