{{- if ne .Values.domain "" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shkeeper
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-shkeeper
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: shkeeper-tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shkeeper
            port:
              number: 5000
{{- end }}
