{{- if .Values.ltc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litecoind-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: litecoind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litecoind
  template:
    metadata:
      labels:
        app: litecoind
    spec:
      containers:

      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/templates/default.conf.template
          subPath: default.conf.template
        - mountPath: /backup
          name: backup
        env:
        - name: SHKEEPER_BACKEND_KEY
          valueFrom:
            secretKeyRef:
              name: shkeeper-btc-key
              key: password


      - name: litecoind
        image: vsyshost/litecoind:0.21.2.2
        {{- if not .Values.ltc.mainnet }}
        command:
        - /shkeeper/litecoind
        - -testnet
        - -rpcport=9332
        - -prune=550
        - -rpcpassword=$LTC_PASSWORD
        - -rpcuser=$LTC_USERNAME
        - -rpcbind=0.0.0.0
        - -rpcallowip=0.0.0.0/0
        - -wallet=shkeeper
        - -walletnotify=/shkeeper/walletnotify.sh %s
        {{- end }}
        env:
          - name: LTC_USERNAME
            valueFrom:
              secretKeyRef:
                name: litecoin-rpc
                key: username
                optional: false
          - name: LTC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: litecoin-rpc
                key: password
                optional: false
          - name: SHKEEPER_BACKEND_KEY
            valueFrom:
              secretKeyRef:
                name: shkeeper-btc-key
                key: password
                optional: false
        volumeMounts:
        - name: litecoind-storage
          mountPath: /root/.litecoin
        - name: backup
          mountPath: /backup
      volumes:
      - name: litecoind-storage
        persistentVolumeClaim:
          claimName: litecoind-claim
      - name: backup
        emptyDir:
          medium: Memory
      - name: nginx-config
        configMap:
          name: nginx-config
{{- end }}
