{{- if .Values.doge_fullnode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dogecoin-fullnode
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: jsonrpc
    port: 22555
    targetPort: 22555
  selector:
    app: dogecoin-fullnode
{{ end }}