{{- if .Values.doge.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: dogecoin-shkeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dogecoin-shkeeper
  ports:
  - name: app-tcp
    port: 6000
    protocol: TCP
{{ end }}