{{- if or .Values.ltc.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: litecoin-shkeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: litecoin-shkeeper
  ports:
  - name: app-tcp
    port: 6000
    protocol: TCP
{{ end }}