{{- if .Values.btc_lightning.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightning-lnbits
  namespace: {{ .Values.namespace }}
  labels:
    app: lightning-lnbits
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: lightning-lnbits
  template:
    metadata:
      labels:
        app: lightning-lnbits
    spec:

      initContainers:
      - name: lightning-lnbits-init
        image:  {{ .Values.btc_lightning.lnbits.image }}
        command:
        - /app/.venv/bin/python
        - /app/setup_lnbits.py
        env:
          - name: LNBITS_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: lightning-lnbits-account
                key: user
          - name: LNBITS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lightning-lnbits-account
                key: password
          - name: DEBUG
            value: "True"
          - name: LNBITS_ADMIN_UI
            value: "false"
          - name: HOST
            value: 127.0.0.1
          - name: PORT
            value: "5000"
          - name: LNBITS_DATA_FOLDER
            value: "./data"
          - name: LNBITS_ALLOWED_FUNDING_SOURCES
            value: "LndRestWallet"
          - name: LNBITS_BACKEND_WALLET_CLASS
            value: LndRestWallet
          - name: LIGHTNING_INVOICE_EXPIRY
            value: "3600"
          - name: LND_REST_ENDPOINT
            value: {{ .Values.btc_lightning.lnd.rest_url }}
          - name: LND_REST_CERT
            value: "/.lnd/tls.cert"
          - name: LND_REST_MACAROON
            value: "/.lnd/data/chain/bitcoin/{{ .Values.btc_lightning.network }}/admin.macaroon"
          - name: LNBITS_USER_DEFAULT_EXTENSIONS
            value: "lnurlp"
          - name: LNBITS_ALLOW_NEW_ACCOUNTS
            value: "false"
          {{- range $name, $value := .Values.btc_lightning.lnbits.extraEnv }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}

        volumeMounts:
        - name: lightning-lnbits
          mountPath: /app/data
        - name: lightning-lnd
          mountPath: /.lnd


      containers:
      - name: lightning-lnbits
        image:  {{ .Values.btc_lightning.lnbits.image }}
        env:
          - name: LNBITS_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: lightning-lnbits-account
                key: user
          - name: LNBITS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lightning-lnbits-account
                key: password
          - name: DEBUG
            value: "True"
          - name: LNBITS_ADMIN_UI
            value: "false"
          - name: HOST
            value: 127.0.0.1
          - name: PORT
            value: "5000"
          - name: LNBITS_DATA_FOLDER
            value: "./data"
          - name: LNBITS_ALLOWED_FUNDING_SOURCES
            value: "LndRestWallet"
          - name: LNBITS_BACKEND_WALLET_CLASS
            value: LndRestWallet
          - name: LIGHTNING_INVOICE_EXPIRY
            value: "3600"
          - name: LND_REST_ENDPOINT
            value: {{ .Values.btc_lightning.lnd.rest_url }}
          - name: LND_REST_CERT
            value: "/.lnd/tls.cert"
          - name: LND_REST_MACAROON
            value: "/.lnd/data/chain/bitcoin/{{ .Values.btc_lightning.network }}/admin.macaroon"
          - name: LNBITS_USER_DEFAULT_EXTENSIONS
            value: "lnurlp"
          - name: LNBITS_ALLOW_NEW_ACCOUNTS
            value: "false"
          {{- range $name, $value := .Values.btc_lightning.lnbits.extraEnv }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}

        ports:
        - containerPort: 5000
          name: web

        volumeMounts:
        - name: lightning-lnbits
          mountPath: /app/data
        - name: lightning-lnd
          mountPath: /.lnd

      volumes:
      - name: lightning-lnbits
        persistentVolumeClaim:
          claimName: lightning-lnbits
      - name: lightning-lnd
        persistentVolumeClaim:
          claimName: lightning-lnd
{{- end }}
