{{ if .Values.btc_lightning.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: lightning-lnbits-account
  namespace: {{ .Values.namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  user: c2hrZWVwZXI=
{{ end }}